force-app/main/default/objects/Trade_Request__c/Trade_Request__c.object-meta.xml
<CustomObject>
    <description>Stores all trade requests submitted by traders</description>
    <label>Trade Request</label>
    <nameField>
        <displayFormat>TRD-{000000}</displayFormat>
        <label>Trade Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Request__c/fields/Entry_Price__c.field-meta.xml
<CustomField>
    <fullName>Entry_Price__c</fullName>
    <label>Entry Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade_Request__c/fields/Trader__c.field-meta.xml
<CustomField>
    <fullName>Trader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trader</label>
    <referenceTo>Trader__c</referenceTo>
    <relationshipLabel>Trade Requests</relationshipLabel>
    <relationshipName>Trade_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trader__c/Trader__c.object-meta.xml
<CustomObject>
    <description>Stores all trader information.</description>
    <label>Trader</label>
    <nameField>
        <label>Trader Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Traders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TradeRequestTriggerHandler.cls
public with sharing class TradeRequestTriggerHandler {

    public void beforeInsert(List<Trade_Request__c> newTrades) {

        for (Trade_Request__c trade : newTrades) {

            Decimal exposure =
                TradeRequestService.calculateExposure(
                    trade.Quantity__c,
                    trade.Entry_Price__c
                );

            if (!TradeRequestService.validateTradingLimit(
                    trade.Trader__c,
                    trade.Quantity__c,
                    trade.Entry_Price__c
                )) {

                trade.addError(
                    'Trade value exceeds the Trading Limit of the Trader.'
                );
            }

        }

    }

    public void beforeUpdate(
        List<Trade_Request__c> newTrades,
        Map<Id, Trade_Request__c> oldMap
    ) {

        // We'll implement business rules here later.

    }

    public void afterInsert(
        List<Trade_Request__c> newTrades
    ) {

        // Future enhancement

    }

    public void afterUpdate(
        List<Trade_Request__c> newTrades,
        Map<Id, Trade_Request__c> oldMap
    ) {

        // Future enhancement

    }

}